sudo: false
language: node_js
node_js:
  - "6.10.3"
before_script:
  - 'npm install'
  - 'npm install -g bower'
  - 'bower install'

script:
  - npm run test-single-run
  - npm run protractor-ci
  - ./modify_api.sh "backend:1234"
  - cat continuumAssessmentPlatform/teamselection/teamselection.js
  - npm run test-single-run

after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js